version: "3.3"
services:
    web: 
        build: .
        container_name: php73
        depends_on:
            - db
        ports:
            - "8000:80"
        volumes:
            - ./src/:/var/www/html
        networks:
            - default
    db:
        container_name: mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: barangay_it_v2_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports: 
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY= 1
        restart: always
        ports:
            - 8899:80 
